# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_ros_control_interface/MoveItControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_7
      - joint_3
      - joint_4
      - joint_5
      - joint_6